// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  GetAddressFindData,
  GetAddressFindResponses,
  GetDeprivationData,
  GetDeprivationResponses,
  GetLiveListingsSearchData,
  GetLiveListingsSearchResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Address Find
 *
 * Search for UK addresses by query string
 */
export const getAddressFind = <ThrowOnError extends boolean = false>(
  options: Options<GetAddressFindData, ThrowOnError>,
): RequestResult<GetAddressFindResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetAddressFindResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ name: "Authorization", type: "apiKey" }],
    url: "/address/find/",
    ...options,
  });

/**
 * Deprivation Index
 *
 * IMD data for any postcode across 10 distinct domains.
 */
export const getDeprivation = <ThrowOnError extends boolean = false>(
  options: Options<GetDeprivationData, ThrowOnError>,
): RequestResult<GetDeprivationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetDeprivationResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ name: "Authorization", type: "apiKey" }],
    url: "/deprivation/",
    ...options,
  });

/**
 * Live Listings
 *
 * Real-time property listings powered by Elasticsearch with advanced market filtering.
 */
export const getLiveListingsSearch = <ThrowOnError extends boolean = false>(
  options?: Options<GetLiveListingsSearchData, ThrowOnError>,
): RequestResult<GetLiveListingsSearchResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetLiveListingsSearchResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ name: "Authorization", type: "apiKey" }],
    url: "/live-listings/search/",
    ...options,
  });
