// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.homedata.co.uk" | (string & {});
};

export type AreaLocationInfo = {
  code?: string;
  name?: string;
};

export type OverallDeprivation = {
  rank?: number;
  decile?: number;
  score?: number;
  label?: string;
  short_label?: string;
  lad_rank?: number;
  lad_rank_description?: string;
};

export type DeprivationDomain = {
  domain?: string;
  label?: string;
  short_label?: string;
  description?: string;
  rank?: number;
  decile?: number;
  score?: number;
  score_label?: string;
  score_short?: string;
  lad_rank?: number;
};

export type DeprivationMetadata = {
  source?: string;
  total_lsoas?: number;
  total_lads?: number;
  score_explanation?: string;
  rank_explanation?: string;
  neighbourhood_explanation?: string;
};

export type DeprivationResponse = {
  postcode?: string;
  lsoa?: AreaLocationInfo;
  lad?: AreaLocationInfo;
  overall?: OverallDeprivation;
  domains?: Array<DeprivationDomain>;
  metadata?: DeprivationMetadata;
};

export type PropertyListing = {
  id?: string;
  street?: string;
  postcode?: string;
  transaction_type?: string;
  latest_status?: string;
  latest_price?: number;
  source?: string;
  bedrooms?: number;
  bathrooms?: number;
  reception_rooms?: number;
  property_type?: string;
  ownership?: string;
  is_new_build?: boolean;
  has_garden?: boolean;
  has_parking?: boolean;
  has_solar_panels?: boolean;
  is_reduced?: boolean;
  times_reduced?: number;
  is_withdrawn?: boolean;
  days_on_market?: number;
  added_date?: string;
  agent_name?: string;
};

export type LiveListingsResponse = {
  count?: number;
  page?: number;
  page_size?: number;
  total_pages?: number;
  results?: Array<PropertyListing>;
};

export type GetDeprivationData = {
  body?: never;
  path?: never;
  query: {
    /**
     * UK Postcode to search (e.g., PO11 0QW).
     */
    postcode: string;
  };
  url: "/deprivation/";
};

export type GetDeprivationResponses = {
  /**
   * Successful response returning area deprivation metrics.
   */
  200: DeprivationResponse;
};

export type GetDeprivationResponse =
  GetDeprivationResponses[keyof GetDeprivationResponses];

export type GetLiveListingsSearchData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * UK Postcode to filter live property market listings (e.g., NR1 1TA).
     */
    postcode?: string;
    /**
     * Unique internal boundary identifier (e.g., 14624).
     */
    boundary_id?: string;
    /**
     * The listing transaction type.
     */
    transaction_type?: "Sale" | "Rent";
    /**
     * Specific number of target bedrooms.
     */
    bedrooms?: number;
    /**
     * Maximum target threshold for bedrooms.
     */
    max_bedrooms?: number;
    /**
     * Minimum price limit.
     */
    min_price?: number;
    /**
     * Maximum price limit.
     */
    max_price?: number;
    /**
     * Comma-separated list of target types (e.g., Detached,Flat).
     */
    property_type?: string;
    /**
     * Comma-separated marketing status strings (e.g., For sale,Sold STC).
     */
    status?: string;
    /**
     * Restricts results to new build developments if present.
     */
    new_builds_only?: string;
    /**
     * Filters only for properties that have undergone price reductions.
     */
    reduced_only?: string;
    /**
     * Toggle to include properties pulled from market.
     */
    include_withdrawn?: string;
    /**
     * Target start window for added date (YYYY-MM-DD).
     */
    date_from?: string;
    /**
     * Target end window for added date (YYYY-MM-DD).
     */
    date_to?: string;
    /**
     * Minimum required days on market.
     */
    min_dom?: number;
    /**
     * Filter for outdoor space.
     */
    has_garden?: string;
    /**
     * Filter for parking access.
     */
    has_parking?: string;
    /**
     * Filter for solar implementations.
     */
    has_solar_panels?: string;
    /**
     * Comma-separated historical construction eras (e.g., 1930-1949,Pre-1919).
     */
    construction_age_band?: string;
    /**
     * Comma-separated classification parameters (e.g., Private,Shared).
     */
    garden_type?: string;
    /**
     * Comma-separated spacing classifications (e.g., Driveway,Garage).
     */
    parking_type?: string;
    /**
     * Worst acceptable alphabetical energy band rating.
     */
    min_epc_band?: string;
    /**
     * Best target alphabetical energy band rating.
     */
    max_epc_band?: string;
    /**
     * Minimum interior dimension limits in square meters.
     */
    min_floor_area?: number;
    /**
     * Maximum interior dimension limits in square meters.
     */
    max_floor_area?: number;
    /**
     * Minimum acceptable sequential marketing adjustments.
     */
    reduction_count_min?: number;
    /**
     * Field and ordering vector parameter (e.g., -added_date).
     */
    sort?: string;
    /**
     * Pagination sequence index anchor.
     */
    page?: number;
    /**
     * Maximum items dispatched inside the nested query loop array.
     */
    page_size?: number;
  };
  url: "/live-listings/search/";
};

export type GetLiveListingsSearchResponses = {
  /**
   * Successful response returning active listings with pagination.
   */
  200: LiveListingsResponse;
};

export type GetLiveListingsSearchResponse =
  GetLiveListingsSearchResponses[keyof GetLiveListingsSearchResponses];
